### ISSUE TITLE
🎨 Custom GUI! Slideshow interaction edition

### ISSUE THREAD

**Issue by grahamearley** [mjavaly/Prairie#102]

**Comment by shoemakerc** [comment]
On branch `chris/custom-inspectors`

Creating this custom GUI is pretty straightforward (thanks `PrairieGUI.drawObjectList`!), and is potentially useful, since it shows the images being added to the slideshow as thumbnails.  However, this doesn't space too well on the inspector:

![Texture Custom GUIs](http://i.imgur.com/wi18uBs.jpg "Yeesh")

Gonna tackle this a bit more to see if I can format the look of this GUI a little better.

**Comment by grahamearley** [comment]
Love the hidden "Yeesh" comment on that image :)
