### ISSUE TITLE
Add Repeatability back to the Interactions GUI

### ISSUE THREAD

**Issue by grahamearley** [mjavaly/Prairie#139]
We left the "repeatable" checkbox out when we made all our custom GUIs. Let's get it back!

**Comment by shoemakerc** [comment]
Gonna put out a rough list of all interactions in our toolbox so far, grouped on my perspective on whether or not we should make the `repeatable` bool checkbox visible or not.  Here's what I have so far:

**Repeatability == visible**
* `AudioInteraction`
* `ComponentToggleInteraction`
* ~~`PromptInteraction`~~
* `TriggerInteraction`

**Repeatability != visible**
* `AssociatedTwineNodes`
* `DebugInteraction`
* `Slideshow`
* `Swivel`
* `Tumble`

I would add my basic reasoning for why I put each interaction in its respective group, but I don't want to make this comment too large.

**Comment by brennan724** [comment]
I think AssociatedTwineNodes should be under != visible.  Because we want that to always be active (cycles).

**Comment by shoemakerc** [comment]
Ooh yeah my bad, that was actually meant to be under != visible in the first place.

**Comment by grahamearley** [comment]
Looks good!

**Comment by cpimhoff** [comment]
The abstract base class,  `PromptInteraction`, shouldn't be on either side of this list, since we don't provide a GUI for it.

Other than that, this seems good to me.

By making `TriggerInteraction` non-repeatable, you can _effectively_ make any interaction non-repeatable, which I like as sort of a back-up workaround for edge cases.

**Comment by cpimhoff** [comment]
bam
